### ISSUE TITLE
Unable to use the web interface

### ISSUE THREAD

**Issue by xldistance** [kvcache-ai/ktransformers#33]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\open-webui\backend\python311\Scripts\ktransformers.exe\__main__.py", line 7, in <module>
  File "E:\open-webui\backend\python311\Lib\site-packages\ktransformers\server\main.py", line 132, in main
    app = create_app()
          ^^^^^^^^^^^^
  File "E:\open-webui\backend\python311\Lib\site-packages\ktransformers\server\main.py", line 44, in create_app
    mount_index_routes(app)
  File "E:\open-webui\backend\python311\Lib\site-packages\ktransformers\server\main.py", line 61, in mount_index_routes
    update_web_port(web_config_file)
  File "E:\open-webui\backend\python311\Lib\site-packages\ktransformers\server\main.py", line 49, in update_web_port
    with open(config_file, "r", encoding="utf-8") as f_cfg:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\open-webui\\backend\\python311\\Lib\\site-packages\\ktransformers\\website/dist\\config.js'
```

**Comment by zengqingfu1442** [comment]
I also got this error with the latest ktransformers, git commit is 0a9c5992.

**Comment by zengqingfu1442** [comment]
Need to build website dir before installing ktransformers. https://kvcache-ai.github.io/ktransformers/en/api/server/website.html
