### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Chain-Mao** [kvcache-ai/ktransformers#90]
My GPU device is L20, the two installation ways are not work for me, could you give me some suggestions?
1. What I run 'bash install.sh'. The error is:
      /root/ktransformers/ktransformers/ktransformers_ext/cpu_backend/cpuinfer.h:45:43: error: using invalid field ‘CPUInfer::enqueue(Func, Obj*, Args ...)::__lambda1::__args’
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 293, in <module>
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "<string>", line 153, in run
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/wheel/_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
          build_ext.build_extensions(self)
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/root/.conda/envs/ktransformers/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 288, in build_extension
        File "/root/.conda/envs/ktransformers/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.
      [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for ktransformers
      Failed to build ktransformers
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ktransformers)

2. When I run pip install ktransformers --no-build-isolation, there is no error, but when I run 'python -m ktransformers.local_chat --model_name deepseek-ai/DeepSeek-V2-Chat-0628 --gguf_path ./DeepSeek-V2-Chat-0628-GGUFA', the error is:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/ktransformers/ktransformers/local_chat.py", line 25, in <module>
    from ktransformers.optimize.optimize import optimize_and_load_gguf
  File "/root/ktransformers/ktransformers/optimize/optimize.py", line 15, in <module>
    from ktransformers.util.custom_gguf import GGUFLoader, translate_name_to_gguf
  File "/root/ktransformers/ktransformers/util/custom_gguf.py", line 27, in <module>
    import KTransformersOps
ImportError: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /root/.conda/envs/ktransformers/lib/python3.11/site-packages/KTransformersOps.cpython-311-x86_64-linux-gnu.so)

**Comment by UnicornChan** [comment]
This issue seems to be very similar to #37 , both involving the absence of libstdc++.so.6. Perhaps the methods mentioned there could useful?
